server:
  poet: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #设置Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
  instance: 
    instance-id: gateway-9527.com #注册中心不使用默认名字 自定义hystrix相关的服务器名称
    prefer-ip-address: true #访问路径可以显示ip地址
    
    
info:
  app.name: zrh-microservicecloud
  company.name: ffcs
  build.artifactId: microspringcloud-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT